docker build -t marcussviniciusa/speedfunnels-backend:v1.0.2 ./backend
docker push marcussviniciusa/speedfunnels-backend:v1.0.2docker build -t marcussviniciusa/speedfunnels-backend:v1.0.2 ./backend
docker push marcussviniciusa/speedfunnels-backend:v1.0.2