version: '3.8'

services:
  # Backend API
  api:
    image: marcussviniciusa/speedfunnels-api:v1
    restart: always
    environment:
      - NODE_ENV=production
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - REDIS_URL=${REDIS_URL}
      - JWT_SECRET=${JWT_SECRET}
      - META_APP_ID=${META_APP_ID}
      - META_APP_SECRET=${META_APP_SECRET}
      - META_ACCESS_TOKEN=${META_ACCESS_TOKEN}
      - META_REDIRECT_URI=${META_REDIRECT_URI}
      - META_CONFIG_ID=${META_CONFIG_ID}
      - META_AD_ACCOUNT_ID=${META_AD_ACCOUNT_ID}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URL=${GOOGLE_REDIRECT_URL}
      - GOOGLE_SERVICE_ACCOUNT_KEY=${GOOGLE_SERVICE_ACCOUNT_KEY}
      - GA_VIEW_ID=${GA_VIEW_ID}
      - GA_CLIENT_EMAIL=${GA_CLIENT_EMAIL}
      - GA_PRIVATE_KEY=${GA_PRIVATE_KEY}
    depends_on:
      - postgres
      - redis
    networks:
      - speedfunnels_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`${API_DOMAIN:-api.speedfunnels.com}`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.services.api.loadbalancer.server.port=3000"

  # ETL Process
  etl:
    image: marcussviniciusa/speedfunnels-etl:v1
    restart: always
    environment:
      - NODE_ENV=production
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - META_APP_ID=${META_APP_ID}
      - META_APP_SECRET=${META_APP_SECRET}
      - META_ACCESS_TOKEN=${META_ACCESS_TOKEN}
      - META_REDIRECT_URI=${META_REDIRECT_URI}
      - META_CONFIG_ID=${META_CONFIG_ID}
      - META_AD_ACCOUNT_ID=${META_AD_ACCOUNT_ID}
      - GOOGLE_SERVICE_ACCOUNT_KEY=${GOOGLE_SERVICE_ACCOUNT_KEY}
      - GA_VIEW_ID=${GA_VIEW_ID}
      - GA_CLIENT_EMAIL=${GA_CLIENT_EMAIL}
      - GA_PRIVATE_KEY=${GA_PRIVATE_KEY}
    depends_on:
      - postgres
    networks:
      - speedfunnels_network

  # Scheduler
  scheduler:
    image: marcussviniciusa/speedfunnels-scheduler:v1
    restart: always
    environment:
      - NODE_ENV=production
    depends_on:
      - etl
    networks:
      - speedfunnels_network

  # Frontend
  frontend:
    image: marcussviniciusa/speedfunnels-frontend:v1
    restart: always
    depends_on:
      - api
    networks:
      - speedfunnels_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${FRONTEND_DOMAIN:-speedfunnels.com}`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

  # External services (using your provided credentials)
  postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - speedfunnels_network

  redis:
    image: redis:7
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - speedfunnels_network

  # Infrastructure
  traefik:
    image: traefik:v2.9
    restart: always
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik_certificates:/letsencrypt
    networks:
      - speedfunnels_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${FRONTEND_DOMAIN:-speedfunnels.com}`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=traefik-auth"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_DASHBOARD_AUTH}"

  portainer:
    image: portainer/portainer-ce:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - speedfunnels_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.${FRONTEND_DOMAIN:-speedfunnels.com}`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

networks:
  speedfunnels_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  portainer_data:
  traefik_certificates:
